### ISSUE TITLE
Ship RSS for any feed from any request containing an appropriate rss header

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#274]

**Comment by matthew-andrews** [comment]
[also support `Accept: application/rss+xml`]

**Comment by commuterjoy** [comment]
Perhaps try to avoid file extensions and vary on the accept header?

This will be good for Google too. It likes RSS over HTML.

**Comment by matthew-andrews** [comment]
yup updated title

**Comment by adgad** [comment]
So I can put in a rule in next-fastly-deploy to allow any request with the header 'Accept: 'application/rss' to come through no matter what - however this has implications that a) we might not want the entire body in the RSS? b) All our apps should reject if not application/rss
