### ISSUE TITLE
Semantic Streams

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#443]
![artboard_1](https://cloud.githubusercontent.com/assets/825088/7723067/6d5cfa8c-fedd-11e4-8199-d6a0082c2354.png)

**Comment by commuterjoy** [comment]
be mobile first! ;) 

/cc @simonwilliamsFT

**Comment by matthew-andrews** [comment]
Remaining things to do:-
- [ ] Drive “CEO” field from CAPI v2…… somehow…… might need a new label
- [ ] Drive “SUB” field from CAPI v2
- [ ] Potentially add a “PAR” when a company has a parent?
