### ISSUE TITLE
Empty “IN…” navs should probably be suppressed?

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#462]
![screen shot 2015-05-22 at 10 39 53](https://cloud.githubusercontent.com/assets/825088/7767988/ebb54492-006e-11e5-9d84-28873e205c21.png)

http://next.ft.com/stream/brandId/N2I3NDY4ODktYTRjMC00NWNkLTgwZDEtNjgyMTgzM2Q2MmZl-QnJhbmRz

**Comment by matthew-andrews** [comment]
cc @ironsidevsquincy

**Comment by i-like-robots** [comment]
Fixed in #488
