### ISSUE TITLE
When in core experience small screen has no secondary nav

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#496]
![screen shot 2015-06-03 at 17 59 27](https://cloud.githubusercontent.com/assets/825088/7966190/5011c7a8-0a1a-11e5-959b-63423d47b853.png)

@i-like-robots

**Comment by i-like-robots** [comment]
So ATM each sub nav is copied into the 'tools' with JS. Rather than do anything clever we can simply duplicate the markup in the template (I know some people don't like this, I don't mind because it's practical). It would be less janky to load too.

**Comment by matthew-andrews** [comment]
seems fine to me ^^  keep an eye on performance impact
