### ISSUE TITLE
pagination for search broken

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-dobi#507]
![image](https://cloud.githubusercontent.com/assets/447559/8010257/9e0d3d2e-0ba6-11e5-96a0-170abcaa7eae.png)

**Comment by matthew-andrews** [comment]
it's because you broke it :P

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-dobi/pull/508

**Comment by matthew-andrews** [comment]
ok it wasn't you.  sorry.

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-dobi/pull/509

**Comment by matthew-andrews** [comment]
fixed :innocent:

**Comment by wheresrhys** [comment]
Give me some credit! I only raised the issue because it weren't me guv
:appropriate_smilie:

On Friday, June 5, 2015, Matt Andrews <notifications@github.com> wrote:

> Closed #507 <https://github.com/Financial-Times/next-dobi/issues/507>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-dobi/issues/507#event-323784750>.
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
