### ISSUE TITLE
‘ORGANISATION INFORMATION’ shown when there is no ‘ORGANISATION INFORMATION’

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#524]
![screen shot 2015-06-12 at 10 07 21](https://cloud.githubusercontent.com/assets/825088/8126921/e1cdc9fe-10ea-11e5-9eb1-71711c6b4548.png)

**Comment by matthew-andrews** [comment]
@i-like-robots

**Comment by i-like-robots** [comment]
We surely shouldn't be loading the organisations sub header when the flag is off... so there's a case in the template here: https://github.com/Financial-Times/next-dobi/blob/master/views/article-list.html#L1-5

And `showSemanticStreamHeader` is assigned here: https://github.com/Financial-Times/next-dobi/blob/master/server/controllers/v1-taxonomy.js#L127

Which is hidden behind a flag here: https://github.com/Financial-Times/next-dobi/blob/master/server/controllers/v1-taxonomy.js#L82

**Comment by matthew-andrews** [comment]
oh yes this is with the flag on…
