### ISSUE TITLE
Live streaming sometimes streams in old content

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-dobi#534]
cc @i-like-robots 

![wat](https://cloud.githubusercontent.com/assets/825088/8169310/a4beb682-13a0-11e5-9602-4e90bad1b41d.gif)

So what I think is happening here is different cache nodes have different versions of the page………

Kind of funny :smile:

**Comment by i-like-robots** [comment]
Surely we're not caching pages for that length of time!? I have two ideas of how to work around this:

1. Include the time of the initial/most recent page update in the query string (may cause loads of cache misses)
2. Test if the last story ID in the response header is on the page already

**Comment by matthew-andrews** [comment]
but if we're on page 2 of a paginated feed we shoudl never have live content stream in, should we?  is that even useful?

**Comment by i-like-robots** [comment]
Different issue https://github.com/Financial-Times/next-dobi/issues/562

**Comment by matthew-andrews** [comment]
oops

**Comment by matthew-andrews** [comment]
totally got confused here
